USE MANTENIMIENTO_PRODUCTO

CREATE TABLE MARCA(
IDMARCA INT IDENTITY(1,1) NOT NULL PRIMARY KEY ,
CODIGO AS('MR'+RIGHT('00'+CONVERT(VARCHAR,IDMARCA),(2))),
NOMBRE NVARCHAR (30) NOT NULL,
DESCRIPCION NVARCHAR(256) NULL,
)

CREATE PROC SP_BUSCARMARCA
@BUSCAR VARCHAR(30)
AS
SELECT * FROM MARCA
WHERE NOMBRE LIKE @BUSCAR + '%'

CREATE PROC SP_INSERTARMARCA
@NOMBRE VARCHAR (30),
@DESCRIPCION VARCHAR(256)
AS
INSERT INTO MARCA VALUES (@NOMBRE,@DESCRIPCION)

CREATE PROC SP_EDITARMARCA
@IDMARCA INT,
@NOMBRE VARCHAR(30),
@DESCRIPCION VARCHAR(256)
AS
UPDATE MARCA SET NOMBRE=@NOMBRE, DESCRIPCION=@DESCRIPCION
WHERE IDMARCA=@IDMARCA


CREATE PROC SP_ELIMINARMARCA
@IDMARCA INT 
AS
DELETE MARCA 
WHERE IDMARCA=@IDMARCA
